version: '3'
services:
  # MySQL database
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: canon2003
      MYSQL_DATABASE: gustodb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  # Node.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_USER: root # Match the username used in the MySQL service
      DB_PASSWORD: canon2003
      DB_NAME: gustodb
